import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from '../../node_modules/next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="absolute top-[5%] left-[6%] text-[#eba941] text-3xl z-10">
          <span>
            <Link href="/">desing</Link>
          </span>
          <span> & </span>
          <Link href="video">video</Link>
        </div>
        <video autoPlay muted loop playsInline>
          <source src="video/portada.mp4" />
        </video>
        <div className={inter.className}>{children}</div>
      </body>
    </html>
  );
}
