import Image from 'next/image';


export default function Home() {
  return (
    <>
      <header>
        <video className='w-full' src="video/gdbanner.mp4" autoPlay muted loop playsInline></video>
      </header>
      <main>
        <section className="relative">
        <video 
          className="absolute w-[36%] top-[19.02%] left-[3.4%]"
          src="video/festime-animacion.mp4" autoPlay muted loop playsInline></video>
          <Image
            src="/festime.png"
            alt="logo"
            width={1500}
            height={1500}
            loading="lazy"
            className="w-full"
          ></Image>
        </section>
        <section>
          <Image
            src="/eterna.png"
            alt="logo"
            width={1500}
            height={1500}
            loading="lazy"
            className="w-full"
          ></Image>
        </section>
        <section>
          <Image
            src="/planifica.png"
            alt="logo"
            width={1500}
            height={1500}
            loading="lazy"
            className="w-full"
          ></Image>
        </section>
        <section>
          <Image
            src="/embarazo.png"
            alt="logo"
            width={1500}
            height={1500}
            loading="lazy"
            className="w-full"
          ></Image>
        </section>
        <section>
          <Image
            src="/harmony.jpg"
            alt="logo"
            width={1500}
            height={1500}
            loading="lazy"
            className="w-full"
          ></Image>
        </section>
        <section>
          <Image
            src="/contraportada.jpg"
            alt="logo"
            width={1500}
            height={1500}
            loading="lazy"
            className="w-full"
          ></Image>
        </section>
        <section>
          <Image
            src="/contenido.jpg"
            alt="logo"
            width={1500}
            height={1500}
            loading="lazy"
            className="w-full"
          ></Image>
        </section>
        <section>
          <Image
            src="/lori.png"
            alt="logo"
            width={1500}
            height={1500}
            loading="lazy"
            className="w-full"
          ></Image>
        </section>
        <section>
          <Image
            src="/congreso.png"
            alt="logo"
            width={1500}
            height={1500}
            loading="lazy"
            className="w-full"
          >
          </Image>
        </section>
      </main>
      <footer></footer>
    </>
  );
}
